language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

before_script:
  - cd mysite
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - black --check .
  - flake8 .
  - coverage run --source=polls manage.py test

after_script:
  - coveralls
